#+HTML:<div align=center><a href="https://github.com/hatlafax/ELSE-grammar-compiler"><img alt="Emacs Logo" width="240" height="240" src="https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg"></a>

#+HTML:</div>

* Antrl v4 grammar to Emacs ELSE template compiler

This is prototype of a compiler that translate Antrl v4 language grammars to Emacs ELSE mode LSE template files.

This is work in progress and currently not for production use.

* Installation

- Install Python
- Install the antlr4 python runtime

  #+begin_example
pip install --user --upgrade antlr4-python3-runtime
  #+end_example

* Usage

  Get help about the command line options:

  #+begin_example
python Antlr4ToElseCompiler.py -h
  #+end_example

  Typically used commands for compiling a grammar to an ELSE template lse file. Option =-i= specifies the
  input directory for the =*.g4= grammar files. Option =-o= specifies the output directory for the produced
  =.lse= ELSE template file. Option =-l= specifies the ELSE language and therefore the name of the =.lse=
  file.

  Options =-p= and =-I=, punctuation characters and valid identifier characters, respectively, are specified
  for the proper ELSE language specification.

  Option =-v= causes the compiler to procuce verbose log ouput. With additionally defining option =-T= a list
  of listener handler names can be provided that allows to filter the verbose logging output.

  #+begin_example
python Antlr4ToElseCompiler.py -i ./grammars -o ./out -l Python -p '*(),;:' -I 'a-zA-Z_0-9-' Python3Parser.g4 Python3Lexer.g4
python Antlr4ToElseCompiler.py -i ./grammars -o ./out -l Python -p '*(),;:' -I 'a-zA-Z_0-9-' -v Python3Parser.g4 Python3Lexer.g4
python Antlr4ToElseCompiler.py -i ./grammars -o ./out -l c++ -p '*(){}[].,;:' -I 'a-zA-Z_0-9-' CPP23.g4
  #+end_example

  The compiler also allows batch processing of grammar files. This works for the grammar files provided
  in the grammar directory, because the language option for these grammars is known by the compiler.
  However, this is useful for testing and not meant for final template file generation because additional
  command line options, e.g. for punctuation, are naively defaulted.

  #+begin_example
python Antlr4ToElseCompiler.py -i ./grammars -o ./out -b
  #+end_example

  Options =--indentation-token=, =--dedentation-token= and =--newline-token= allow the definition of a distinguished
  lexer tokens that are used for shapeing the generated ELSE template lse file.

  Options =-w= causes the compiler to generate a file /language.lst/ that list of all placeholders that finds its way
  into the /language.lse/ template file. Starting from that, the user can create a mapping file /language.map/ of
  placeholders that allows the definition of an alternative placeholder name that is then used in the /language.lse/
  file to get a more pleasing template file. This mapping file is used when providing option =-r= to the compiler.

  The mapping file contains exactly one line for each placeholder to be mapped with the old and new name separated
  by a separator string ~=> ::~, that is:

  ~placeholdder => :: mapped placeholder~

  Example:  ~(s_expr ∣ n_expr) => :: s_or_n_expr~

  Option =-x= causes the compiler to read a file /language.spc/ that has the same format as the /language.map/
  file and defines exception rules on each line with respect to omitting space separator charactes between
  parse tokens in the final ELSE template lse file.

  Finally, option =-E= allows the definition of a list of terminal tokens for which the compiler should generate
  terminal placeholder entries in the template lse file although the terminal specification is missing from the
  grammar. This option is useful in case that you are dealing with a reduced grammar file without any lexer
  information.

  At last a complete command line used for the generation of a Python language LSE template file...

  #+begin_example
python Antlr4ToElseCompiler.py -i ./grammars -o ./out -l python -p '*(),;' -I 'a-zA-Z_0-9-' -w -r -x -v Python3Parser.g4 Python3Lexer.g4
  #+end_example

  with the following files involved:

  | File               | Remark                                            | Read from   | Written to | Option |
  |--------------------+---------------------------------------------------+-------------+------------+--------|
  | =Python3Parser.g4= | The parsar [[https://github.com/antlr/grammars-v4][ANTLR v4 grammar]] file for Python 3.    | =./grammar= |            |        |
  | =Python3Lexer.g4=  | The lexer [[https://github.com/antlr/grammars-v4][ANTLR v4 grammar]] file for Python 3.     | =./grammar= |            |        |
  | =Python.lse=       | The generated [[https://github.com/peter-milliken/ELSE][Emacs ELSE]] v2 Python template file. |             | =./out=    |        |
  | =Python.lst=       | The generated placeholder list.                   |             | =./out=    | =-w=   |
  | =Python.map=       | The considered placeholder mapping file.          | =./grammar= |            | =-r=   |
  | =Python.spc=       | The considered no space separator pattern file.   | =./grammar= |            | =-x=   |

... and a complete command line used for the generation of a C++ language LSE template file.

  #+begin_example
python Antlr4ToElseCompiler.py -i ./grammars -o ./out -l c++ -p '*(){}[].,;:' -I 'a-zA-Z_0-9-' CPP23.g4
  #+end_example

* Antrlv4 grammar extensions

  The parser allows additional annotations for ELSE in the rule specification by the optional =annotationsSpec= rule.

  | annotation       | value                    | example     | result                         |
  |------------------+--------------------------+-------------+--------------------------------|
  | =separator=        | arbitrary                | =", "=        | ~/SEPARATOR=", "~                |
  |------------------+--------------------------+-------------+--------------------------------|
  | =substitute-count= | number                   | ="7"=         | ~/SUBSTITUTE_COUNT=7~            |
  | =substitute_count= | number                   | ="7"=         | ~/SUBSTITUTE_COUNT=7~            |
  |------------------+--------------------------+-------------+--------------------------------|
  | =description=      | text                     | ="some text"= | ~/DESCRIPTION="Some text"~       |
  |------------------+--------------------------+-------------+--------------------------------|
  | =duplication=      | ~"context-dependent"~,     |             | ~/DUPLICATION=CONTEXT_DEPENDENT~ |
  |                  | ~"context_dependent"~,     |             | ~/DUPLICATION=CONTEXT_DEPENDENT~ |
  |                  | ~"context"~,               |             | ~/DUPLICATION=CONTEXT_DEPENDENT~ |
  |                  | ~"horizontal",~            |             | ~/DUPLICATION=HORIZONTAL~        |
  |                  | ~"vertical"~               | ="vertical"=  | ~/DUPLICATION=VERTICAL~          |
  |------------------+--------------------------+-------------+--------------------------------|
  | =substitute-type=  | ~"auto"~ or other text     | ="auto"=      | ~/AUTO_SUBSTITUTE~               |
  | =substitute_type=  |                          | ="noauto"=    | ~/NOAUTO_SUBSTITUTE~             |
  | =auto-substitute=  | ~"1", "true", "on", "yes"~ | ="true"=    | ~/AUTO_SUBSTITUTE~               |
  | =auto_substitute=  |                          | ="off"=       | ~/NOAUTO_SUBSTITUTE~             |
  |------------------+--------------------------+-------------+--------------------------------|

  Examples: from the c++ grammar

  #+begin_example
attribute-specifier
  annotations (separator = ', ', substitute_count='7', description='Some other text', duplication='context', substitute_type='noauto')
  : '[[' attribute-using-prefix ? attribute-list ']]'
  | alignment-specifier
  ;
  #+end_example


* Dependencies
- [[https://www.antlr.org/][ANTLR v4]] >= 4.9.2

  The Antlr v4 Python parser code was generated with Antlr v4 4.9.2.

- [[https://www.python.org/][Python]] >= 3.8.5
- [[https://pypi.org/project/antlr4-python3-runtime/][antlr4-python3-runtime 4.9.2]]
- [[https://www.gnu.org/software/emacs/][Emacs]] >= 27
- [[https://github.com/peter-milliken/ELSE][Emacs ELSE]] v2
- [[https://github.com/antlr/grammars-v4][ANTLR v4 grammars]]

  The grammars found in the grammar folder of this repository are copies from the [[https://github.com/antlr/grammars-v4][ANTLR v4 grammars]].
  They are provided only for simplifying testing. They will not be synchronized with future changes.

  There is no single license for the grammars, each grammar has its own license. Check inside the grammar files for licensing terms.

  See also: [[https://github.com/antlr/grammars-v4/wiki][ANTLR v4 grammars Wiki]]

* Disclaimer

 This is an experimental project. Do not rely on it. It is work in progress and it is open if this will lead to a valuable software component.

* Remarks

- This compiler builds on a modification of the original ANTLRv4 grammar (=ANTLRv4Lexer.g4, ANTLRv4Parser.g4=).
  This modification implements an extension that is taken from [[https://www.python.org/dev/peps/pep-0617/][PEP 617 -- New PEG parser for CPython]]. This extension
  allows the usage of the following grammar construct =s.e+= to express the equivalent construct =e (s e)*=.

  Examples:
  | Original construct                             | Extension construct      | LSE file entry           |
  |------------------------------------------------+--------------------------+--------------------------|
  | =(expression (',' expression)*)=               | =','.expression+=        | ={expression}...=        |
  | =(small_stmt (';' small_stmt)*)=               | =';'.small_stmt+=        | ={small_stmt}...=        |
  | =(NAME (',' NAME)*)=                           | =','.NAME+=              | ={NAME}...=              |
  | =((s_expr ∣ n_expr) (',' (s_expr ∣ n_expr))*)= | =','.(s_expr ∣ n_expr)+= | ={(s_expr ∣ n_expr)}...= |


- Python provides a [[https://docs.python.org/3.9/reference/grammar.html][full grammar specification]]. This specification (=./grammars/Python396.peg=) written in
  a mixture of [[https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form][EBNF]] and [[https://en.wikipedia.org/wiki/Parsing_expression_grammar][PEG]] plus some handcrafted extensions detailed in [[https://www.python.org/dev/peps/pep-0617/][PEP 617 -- New PEG parser for CPython]]
  is not directly usable by the compiler. The compiler only handles [[https://github.com/antlr/grammars-v4/tree/master/antlr/antlr4][ANTLR v4]] (extended by the s.e+ construnct)
  out of the box. File =./grammars/Python396_Antlr.g4= contains a transformed version of this original Python PEG
  grammar file. By comparing these two files, one can directly see the necessary transformation steps.


- Finally, a language grammar does need some fine tuning in order to get a viable [[https://github.com/peter-milliken/ELSE][Emacs ELSE]] template file.
  Newlines and indentation are of especially importance for that matter. The final grammar file is
  =./grammar/Python396.g4=.

* Limitations / Known Issues

- Tested on Windows operating system only.


- The generated LSE files nevertheless need additional handcrafting to be useful for Emacs usage.
  However, the generated files  shorten the time to get a new proper template file considerably.

* License: Boost Software License 1.0

- [[https://github.com/hatlafax/ELSE-grammar-compiler/blob/main/LICENSE][Boost Software License - Version 1.0 - August 17th, 2003]]

- The grammars found in the grammar folder of this repository are copies from the [[https://github.com/antlr/grammars-v4][ANTLR v4 grammars]].
  There is no single license for the grammars, each grammar has its own license. Check inside the grammar files for licensing terms.

* Psimacs Integration

** Constants

#+begin_src emacs-lisp
(defconst psimacs/config/else-grammar-compiler-dir
  (psimacs/file-system/concat-directory psimacs/config/system-utils-dir "ELSE-grammar-compiler")
  "The psimacs ELSE grammar compiler directory.")

(defconst psimacs/config/else-grammar-compiler-out-dir
  (psimacs/file-system/concat-directory psimacs/config/else-grammar-compiler-dir "out")
  "The psimacs ELSE grammar compiler output directory.")

(defconst psimacs/config/else-grammar-compiler-py
  (psimacs/file-system/concat-file psimacs/config/else-grammar-compiler-dir "Antlr4ToElseCompiler.py")
  "The psimacs ELSE grammar compiler python programm.")

(defconst psimacs/config/ebnf-convert-dir
  (psimacs/file-system/concat-directory psimacs/config/else-grammar-compiler-dir "tools/ebnf-convert")
  "The psimacs ebnf grammar converter directory.")

(defconst psimacs/config/ebnf-railroad-dir
  (psimacs/file-system/concat-directory psimacs/config/else-grammar-compiler-dir "tools/railroad")
  "The psimacs ebnf railroad directory.")

(defconst psimacs/config/ebnf-convert-jar-file
  (psimacs/file-system/concat-file psimacs/config/ebnf-convert-dir "ebnf-convert.war")
  "The psimacs ebnf grammar converter jar file.")

(defconst psimacs/config/ebnf-railroad-jar-file
  (psimacs/file-system/concat-file psimacs/config/ebnf-railroad-dir "rr.war")
  "The psimacs ebnf railroad jar file.")
#+end_src

** ELSE Grammar Compiler

ELSE, the Emacs Language Sensitive Editor, is a system for template generation
aimed at reducing the amount of user typing and to operate seamlessly with a minimum of
interference to the user.
ELSE is implemented as a minor mode and can work with any major mode. As ELSE is
invoked the first time for each major mode, it will load a template file specific to that mode.

The ELSE grammar compiler is a tool written specifically to generate these ELSE template files
from an [[https://www.antlr.org/][ANTLR]] language grammar specification.

The tools provided in this section provide a simple workflow for working on a ANTLR grammar
file and creating a final ELSE template file ready to use in *Psimacs*.

Reference:
- [[https://github.com/hatlafax/ELSE-grammar-compiler][ELSE-grammar-compiler]]
- [[https://github.com/hatlafax/ELSE][ELSE fork by me]]
- [[https://github.com/peter-milliken/ELSE][ELSE]]
- [[https://www.antlr.org/][ANTLR]]

This simplistic ANTLRv4 major mode implementation allows to work on a ANTLRv4 file buffer. It provides
syntax highlighting and supports the special /annotation system/ that has been added to the ANTLRv4 specification
in order to provide extra meta information for the ELSE framework.

#+attr_html: :class styledtable
| Key binding | Command                                               | Description                                                                                |
|-------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------|
| =C-c C-c=     | =M-x psimacs/antlrv4/create-else-grammar=               | Create a ELSE language specification from the ANTLRv4 grammar found in the current buffer. |
| =C-c C-v=     | =M-x psimacs/antlrv4/create-visualization-from-grammar= | Create a HTML visualization of the ANTLRv4 grammar found in the current buffer.            |
|-------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------|

#+begin_src emacs-lisp
;;
;; Support for ANTLRv4
;;
(use-package antlrv4-mode
  :straight nil
  :config
        (defun psimacs/antlrv4/create-else-grammar ()
          "Create a ELSE language specification from the ANTLRv4 grammar found in the current buffer."
          (interactive)
          (when (eq major-mode 'antlrv4-mode)
            (save-buffer)
            (save-excursion
              (let* (
                      (language (psimacs/ui/internal/select-from-item-list "Provide a target language: " '(
                        "ada" "c" "c++" "cmake" "csharp" "emacs-lisp" "java" "javascript" "latex"
                       "modelica" "php" "typescript" "ecmascript" "python" "pascal" "rust" "scala"
                       "clojure" "golang" "dot" "erlang" "html" "prolog" "restructuredtext" "ruby"
                       "texinfo"
                      ) 2))
                      (f-dir  (file-name-directory buffer-file-name))
                      (f-name (file-name-nondirectory buffer-file-name))
                      (out-dir psimacs/config/else-grammar-compiler-out-dir)
                      (out-file (concat psimacs/config/else-grammar-compiler-out-dir language ".lse"))
                      (res-file (concat psimacs/config/else-lse-dir language ".lse"))
                      (bck-file (concat psimacs/config/else-lse-dir language ".lse~"))
                      (placeholder nil)
                    )

                (when (re-search-backward "^\\([[:alnum:]_-]+\\)[[:space:]]*$" nil t)
                  (setq placeholder (match-string 1))
                )

                (make-directory psimacs/config/else-grammar-compiler-out-dir t)
                (when (file-exists-p out-file)
                  (delete-file out-file)
                )

                ;(message "%s"
                (shell-command
                    (concat
                        psimacs/config/python-runtime-exe
                        " "
                        psimacs/config/else-grammar-compiler-py
                        " -i " f-dir " -o " out-dir " -l " language " -p '*(){}[].,;:'" " -I 'a-zA-Z_0-9-' " f-name
                    )
                )

                (when (file-exists-p out-file)
                  (when (file-exists-p res-file)
                    (while (file-exists-p bck-file)
                      (setq bck-file (concat bck-file "~"))
                    )
                    (rename-file res-file bck-file)
                  )

                  (let ((res-file-buffer (get-file-buffer res-file)))
                    (copy-file out-file res-file)
                    (if res-file-buffer
                        (progn
                          (revert-buffer res-file-buffer t t)
                          (pop-to-buffer res-file-buffer)
                        )
                      (find-file-other-window res-file)
                    )

                    (goto-char (point-min))
                    (else-compile-buffer)

                    (message "placeholder = %s" placeholder)

                    (when placeholder
                      (goto-char (point-min))
                      (re-search-forward (concat "DEFINE PLACEHOLDER[[:blank:]]+\"?" placeholder "\"?[[:blank:]]*$") nil t)
                      (recenter 1)
                    )
                  )
                )
              )
            )
          )
        )

        (defun psimacs/antlrv4/create-visualization-from-grammar ()
          "Create a HTML visualization of the ANTLRv4 grammar found in the current buffer."
          (interactive)
          (when (eq major-mode 'antlrv4-mode)
            (save-buffer)
            (let (
                    (grammar-copy-file (concat (file-name-sans-extension (buffer-file-name)) "-tmp" (file-name-extension (buffer-file-name) t)))
                    (ebnf-file (concat (file-name-sans-extension (buffer-file-name)) ".ebnf"))
                    (html-file (concat (file-name-sans-extension (buffer-file-name)) ".html"))
                    (old-buffer (current-buffer))
                 )

              (when (file-exists-p grammar-copy-file)
                (delete-file grammar-copy-file)
              )

              (when (file-exists-p ebnf-file)
                (delete-file ebnf-file)
              )

              (when (file-exists-p html-file)
                (delete-file html-file)
              )

              (with-temp-buffer
                (insert-buffer-substring old-buffer)

                 (goto-char (point-min))

                ;; remove all annotation lines
                (delete-matching-lines "^[[:blank:]]*annotations[[:blank:]]*(.*")

                (write-region (point-min)
                              (point-max) grammar-copy-file t)
              )

              (when (file-exists-p grammar-copy-file)
                (shell-command
                          (concat
                              psimacs/config/java-runtime-exe
                              " -jar "
                             psimacs/config/ebnf-convert-jar-file
                              " -noinline "
                              grammar-copy-file
                              " > "
                              ebnf-file))

                (when (file-exists-p ebnf-file)
                  (shell-command
                          (concat
                              psimacs/config/java-runtime-exe
                              " -jar "
                              psimacs/config/ebnf-railroad-jar-file
                              " -keeprecursion -nofactoring -noinline -html "
                              ebnf-file
                              " > "
                              html-file))

                  (delete-file ebnf-file)

                  (when (file-exists-p html-file)
                    ;(browse-url html-file)
                    (eaf-open-browser-other-window (concat "file://" html-file))
                  )
                )
                (delete-file grammar-copy-file)
              )
            )
          )
        )

  :bind (
           :map antlrv4-mode-map
           ("C-c C-c"     . psimacs/antlrv4/create-else-grammar)
           ("C-c C-v"     . psimacs/antlrv4/create-visualization-from-grammar)
        )

)
#+end_src
