#+HTML:<div align=center><a href="https://github.com/hatlafax/ELSE-grammar-compiler"><img alt="Emacs Logo" width="240" height="240" src="https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg"></a>

#+HTML:</div>

* Antrl v4 grammar to Emacs ELSE template compiler

This is prototype of a compiler that translate Antrl v4 language grammars to Emacs ELSE mode LSE template files.

This is work in progress and currently not for production use.

* Installation

- Install Python
- Install the antlr4 python runtime

  #+begin_example
  pip install antlr4-python3-runtime
  #+end_example

* Dependencies
- [[https://www.antlr.org/][ANTLR v4]] >= 4.9.2

  The Antlr v4 Python parser code was generated with Antlr v4 4.9.2.

- [[https://www.python.org/][Python]] >= 3.8.5
- [[https://pypi.org/project/antlr4-python3-runtime/][antlr4-python3-runtime 4.9.2]]
- [[https://www.gnu.org/software/emacs/][Emacs]] >= 27
- [[https://github.com/peter-milliken/ELSE][Emacs ELSE]] v2
- [[https://github.com/antlr/grammars-v4][ANTLR v4 grammars]]

  The grammars found in the grammar folder of this repository are copies from the [[https://github.com/antlr/grammars-v4][ANTLR v4 grammars].
  They are provided only for simplifying testing. They will not be synchronized with future changes.

  There is no single license for the grammars, each grammar has its own license. Check inside the grammar files for licensing terms.

  See also: [[https://github.com/antlr/grammars-v4/wiki][ANTLR v4 grammars Wiki]]

* Disclaimer

 This is an experimental project. Do not rely on it. It is work in progress and it is open if this will lead to a valuable software component.

* Limitations / Known Issues

- Tested on Windows operating system only

* License: Boost Software License 1.0

- [[https://github.com/hatlafax/ELSE-grammar-compiler/blob/main/LICENSE][Boost Software License - Version 1.0 - August 17th, 2003]]

- The grammars found in the grammar folder of this repository are copies from the [[https://github.com/antlr/grammars-v4][ANTLR v4 grammars].
  There is no single license for the grammars, each grammar has its own license. Check inside the grammar files for licensing terms.
